version: '2'

services:

  proxy:
    image: proxy:latest
    build: 
      context: .
      dockerfile: Dockerfile.proxy
    restart: always
    privileged: false
    ports:
      - 80:80
    links:
      - api-server

  mongodb:
    image: daocloud.io/library/mongo:3.5
    restart: always
    privileged: false
    volumes:
      - /data/db:/data/db

  redis:
    image: daocloud.io/library/redis:3.2.8-alpine
    restart: always
    privileged: false

  crawler:
    image: crawler_scrapy:latest
    build:
      context: ./crawler_scrapy
      dockerfile: Dockerfile
    links:
      - mongodb
      - redis
  
  api-server:
    image: api-server:latest
    build:
      context: ./api-server
      dockerfile: Dockerfile
    links:
      - mongodb
      - redis
