version: '2'

services:

  nginx:
    image: nginx:latest
    build: 
      context: .
      dockerfile: Dockerfile.nginx
    restart: always
    privileged: false
    ports:
      - 80:80

  mongodb:
    image: daocloud.io/library/mongo:3.5
    restart: always
    privileged: false
    volumes:
      - /tmp/db:/data/db

  redis:
    image: daocloud.io/library/redis:3.2.8-alpine
    restart: always
    privileged: false

  crawler:
    image: crawler_scrapy:latest
    build:
      context: ./crawler_scrapy
      dockerfile: Dockerfile
    links:
      - mongodb
      - redis
    volumes:
      - /Users/beilunyang/Code/manhua/crawler_scrapy:/wwwroot
  
  api-server:
    image: api-server:dev
    build:
      context: ./api-server
      dockerfile: Dockerfile.dev
    links:
      - mongodb
      - redis
    volumes:
      - /Users/beilunyang/Code/manhua/api-server:/wwwroot
