version: '2'

services:

  proxy:
    image: proxy:dev
    build: 
      context: .
      dockerfile: Dockerfile.dev.proxy
    restart: always
    privileged: false
    ports:
      - 8080:8080
      - 2333:2333
    links:
      - api-server

  mongodb:
    image: daocloud.io/library/mongo:3.5
    restart: always
    privileged: false
    volumes:
      - /usr/local/var/mongodb:/data/db
    ports:
      - 27777:27017

  redis:
    image: daocloud.io/library/redis:3.2.8-alpine
    restart: always
    privileged: false
  
  api-server:
    image: api-server:dev
    build:
      context: ./api-server
      dockerfile: Dockerfile.dev
    links:
      - mongodb
      - redis
    volumes:
      - /Users/beilunyang/Code/manhua/api-server:/wwwroot
