FROM daocloud.io/library/python:latest
MAINTAINER beilunyang <786220806@qq.com>
RUN apt-get -y update && apt-get install -y cron
ENV DIR /wwwroot
RUN mkdir $DIR
WORKDIR $DIR
ADD . $DIR
RUN pip install -r requirements.txt
CMD  ["scrapy", "crawl", "comic"]